# Generated by Django 4.0.3 on 2022-05-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Країна')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Текст посилання')),
                ('link', models.CharField(max_length=150, verbose_name='Посилання')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва поселення')),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення поселення')),
                ('slug', models.SlugField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.country')),
            ],
        ),
        migrations.CreateModel(
            name='History_Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Назва об'єкту")),
                ('about', models.TextField(verbose_name="Опис об'єкту")),
                ('slug', models.SlugField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
            ],
        ),
    ]
