# Generated by Django 4.0.3 on 2022-05-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_object',
            name='layout',
            field=models.FileField(upload_to='layout', verbose_name=".zip архів з макетом об'єкту"),
        ),
    ]
